import { Check, Circle, Code2, ExternalLink, Layers3 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { progression } from "@/data/platform";

const labels = ["L0", "L1", "L2", "L3", "L4", "L5", "L6", "L7"];

export default function TechnologiesPage() {
  return <div className="space-y-6"><section className="border-b border-white/[.07] pb-6"><div className="mb-2 text-[10px] font-bold uppercase tracking-[.18em] text-cyan-300">Developer platform</div><h1 className="text-3xl font-semibold tracking-tight">Engineering progression</h1><p className="mt-2 max-w-3xl text-sm leading-relaxed text-slate-500">Every integration advances from a small correct foundation into justified production complexity. Implemented levels have source paths and verification commands below; runtime acceptance is recorded separately in the test center; open cells show planned engineering work.</p></section>
    <Card className="overflow-hidden"><div className="grid grid-cols-[minmax(180px,1.4fr)_repeat(8,minmax(48px,.45fr))] border-b border-white/[.07] bg-white/[.02] px-5 py-3"><div className="text-[9px] font-bold uppercase tracking-[.15em] text-slate-500">Technology</div>{labels.map(label=><div key={label} className="text-center text-[9px] font-bold text-slate-600">{label}</div>)}</div>
      {progression.map((technology)=><div key={technology.id} className="grid grid-cols-[minmax(180px,1.4fr)_repeat(8,minmax(48px,.45fr))] items-center border-b border-white/[.06] px-5 py-4 last:border-0 hover:bg-white/[.018]"><div><div className="flex items-center gap-2 text-xs font-semibold"><Code2 size={14} className="text-cyan-300"/>{technology.name}</div><div className="mt-1 text-[9px] text-slate-600">{technology.owner} · max implemented L{technology.implemented}</div></div>{technology.levels.map((title,index)=><div key={title} className="group relative flex justify-center" title={`${labels[index]} — ${title}`}><div className={`grid size-6 place-items-center rounded-md border ${index <= technology.implemented ? "border-cyan-300/20 bg-cyan-300/10 text-cyan-300" : "border-white/[.07] bg-white/[.02] text-slate-700"}`}>{index <= technology.implemented ? <Check size={12}/> : <Circle size={10}/>}</div></div>)}</div>)}</Card>
    <section className="grid gap-4 lg:grid-cols-2">{progression.map((technology)=><Card key={technology.id} className="p-5"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><Layers3 size={15} className="text-cyan-300"/><h2 className="text-sm font-semibold">{technology.name}</h2></div><p className="mt-1 text-[10px] text-slate-500">{technology.levels[technology.implemented]}</p></div><Badge tone="info">L{technology.implemented} implemented</Badge></div><div className="mt-4 border-t border-white/[.07] pt-4"><div className="mb-2 text-[9px] font-bold uppercase tracking-[.14em] text-slate-600">Repository paths</div>{technology.paths.map(path=><div key={path} className="mt-1 flex items-center gap-2 font-mono text-[10px] text-slate-400"><ExternalLink size={10}/>{path}</div>)}</div></Card>)}</section>
    <Card className="p-5"><div className="text-[9px] font-bold uppercase tracking-[.14em] text-slate-600">Verification, evolution, and work</div><div className="mt-4 grid gap-4 md:grid-cols-3">{progression.map((technology)=><div key={technology.id} className="border-l border-white/[.08] pl-3"><div className="text-xs font-semibold">{technology.name}</div>{technology.tests.map(test=><div key={test} className="mt-1 font-mono text-[9px] text-emerald-300/80">{test}</div>)}<div className="mt-2 text-[9px] text-slate-500">{technology.evolution}</div><Badge className="mt-2" tone="neutral">{technology.workItem}</Badge></div>)}</div></Card>
  </div>;
}
