"""Resettable lifecycle entry point for the database query-plan lab."""

from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
import sys

from query_plan_lab import (
    benchmark_lab,
    prepare_lab,
    reset_generated_state,
)

LAB_DIR = pathlib.Path(__file__).resolve().parent
REPOSITORY_ROOT = LAB_DIR.parents[2]
STATE_DIR = LAB_DIR / ".lab-state"


def start() -> None:
    """Build deterministic data and capture the before/after query plans."""

    reset_generated_state(STATE_DIR)
    evidence_path = prepare_lab(STATE_DIR)
    evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
    before = " | ".join(step["detail"] for step in evidence["before"]["plan"])
    after = " | ".join(step["detail"] for step in evidence["after"]["plan"])
    print(f"ready: seeded {evidence['dataset']['row_count']} deterministic projects")
    print(f"before: {before}")
    print(f"after:  {after}")
    print(f"evidence: {evidence_path.relative_to(REPOSITORY_ROOT)}")


def test() -> None:
    """Run isolated unit tests after confirming the lifecycle was started."""

    if not (STATE_DIR / "state.json").exists():
        raise RuntimeError("start the lab before testing")
    subprocess.run(  # noqa: S603 - fixed interpreter and repository-owned test directory
        [
            sys.executable,
            "-m",
            "unittest",
            "discover",
            "-s",
            str(LAB_DIR),
            "-p",
            "test_*.py",
        ],
        cwd=REPOSITORY_ROOT,
        check=True,
    )
    print("pass: results are identical, the indexed plan is used, and reset is safe")


def benchmark() -> None:
    """Capture non-gating timing samples alongside stable plan evidence."""

    report_path = benchmark_lab(STATE_DIR)
    report = json.loads(report_path.read_text(encoding="utf-8"))
    print(
        "benchmark: "
        f"before median={report['before']['median_ms']:.6f} ms; "
        f"after median={report['after']['median_ms']:.6f} ms"
    )
    print("note: timings are illustrative; plan structure and correctness are the stable gates")
    print(f"report: {report_path.relative_to(REPOSITORY_ROOT)}")


def reset() -> None:
    """Remove only the database and evidence generated by this lab."""

    reset_generated_state(STATE_DIR)
    print("reset: generated database, plan evidence, benchmark, and state removed")


def verify() -> None:
    """Exercise the complete lifecycle and guarantee cleanup even on failure."""

    try:
        start()
        test()
        benchmark()
    finally:
        reset()


def parse_args() -> argparse.Namespace:
    """Parse the intentionally small, allowlisted lifecycle command surface."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "action", choices=("start", "test", "benchmark", "reset", "verify")
    )
    return parser.parse_args()


def main() -> None:
    """Dispatch one explicit lifecycle action."""

    actions = {
        "start": start,
        "test": test,
        "benchmark": benchmark,
        "reset": reset,
        "verify": verify,
    }
    args = parse_args()
    actions[args.action]()


if __name__ == "__main__":
    main()
