"""Resettable lifecycle entry point for the SQLite isolation/locking lab."""

from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
import sys

from isolation_lock_lab import prepare_lab, reset_generated_state

LAB_DIR = pathlib.Path(__file__).resolve().parent
REPOSITORY_ROOT = LAB_DIR.parents[2]
STATE_DIR = LAB_DIR / ".lab-state"


def start() -> None:
    """Create fresh state and capture both two-connection experiments."""

    reset_generated_state(STATE_DIR)
    evidence_path = prepare_lab(STATE_DIR)
    evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
    snapshot = evidence["reader_snapshot"]
    writer_lock = evidence["writer_lock"]
    print(
        "snapshot: "
        f"inside={snapshot['value_inside_original_snapshot']}; "
        f"after commit={snapshot['value_after_reader_commit']}"
    )
    print(
        "writer lock: "
        f"{writer_lock['busy_error_name']} with "
        f"busy_timeout={writer_lock['configured_busy_timeout_ms']} ms; retry committed"
    )
    print(f"evidence: {evidence_path.relative_to(REPOSITORY_ROOT)}")


def test() -> None:
    """Run isolated regression tests after the lifecycle has been started."""

    if not (STATE_DIR / "state.json").exists():
        raise RuntimeError("start the lab before testing")
    subprocess.run(  # noqa: S603 - fixed interpreter and repository-owned test path
        [
            sys.executable,
            "-m",
            "unittest",
            "discover",
            "-s",
            str(LAB_DIR),
            "-p",
            "test_*.py",
        ],
        cwd=REPOSITORY_ROOT,
        check=True,
    )
    print("pass: snapshot, lock, timeout, retry, evidence, and reset invariants hold")


def reset() -> None:
    """Remove only files generated by this lab."""

    reset_generated_state(STATE_DIR)
    print("reset: database, WAL sidecars, evidence, and state removed")


def verify() -> None:
    """Exercise the entire lab and guarantee cleanup if any step fails."""

    try:
        start()
        test()
    finally:
        reset()


def parse_args() -> argparse.Namespace:
    """Parse the deliberately allowlisted lifecycle commands."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("start", "test", "reset", "verify"))
    return parser.parse_args()


def main() -> None:
    """Dispatch exactly one lifecycle action."""

    actions = {"start": start, "test": test, "reset": reset, "verify": verify}
    actions[parse_args().action]()


if __name__ == "__main__":
    main()
